import { BiomedTaskSample, HypothesisRecord } from '../types.js';

export function generateInitialHypotheses(
  sample: BiomedTaskSample,
): HypothesisRecord[] {
  const positiveRootId = `H-positive-${sample.sampleIndex}`;
  const negativeRootId = `H-negative-${sample.sampleIndex}`;

  return [
    {
      id: positiveRootId,
      statement: 'The queried drug-protein-disease relationship exists.',
      kind: 'positive',
      status: 'open',
      topicKey: 'root-positive',
      childIds: [
        `H-criterion-drug-target-${sample.sampleIndex}`,
        `H-criterion-protein-disease-${sample.sampleIndex}`,
        `H-criterion-disease-target-${sample.sampleIndex}`,
        `H-criterion-graph-specificity-${sample.sampleIndex}`,
      ],
      depth: 0,
      frontier: false,
      dependencyMode: 'all',
      requiredChecks: ['resolve all positive child hypotheses'],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
    {
      id: negativeRootId,
      statement:
        'The queried drug-protein-disease relationship is unsupported or false.',
      kind: 'negative',
      status: 'open',
      topicKey: 'root-negative',
      childIds: [],
      depth: 0,
      frontier: false,
      dependencyMode: 'all',
      requiredChecks: [
        'evaluate the positive root before settling the negative root',
      ],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
    {
      id: `H-criterion-drug-target-${sample.sampleIndex}`,
      statement:
        'The drug side provides direct mechanism or target evidence for the queried protein.',
      kind: 'criterion',
      status: 'open',
      topicKey: 'criterion.drug-target',
      parentId: positiveRootId,
      childIds: [],
      depth: 1,
      frontier: true,
      dependencyMode: 'any',
      targetedRoles: ['drug'],
      requiredChecks: [
        'drug-protein evidence',
        'mechanism or target evidence',
        'drug-side biological support',
      ],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
    {
      id: `H-criterion-protein-disease-${sample.sampleIndex}`,
      statement:
        'The protein side provides disease-specific relevance for the queried disease.',
      kind: 'criterion',
      status: 'open',
      topicKey: 'criterion.protein-disease',
      parentId: positiveRootId,
      childIds: [],
      depth: 1,
      frontier: true,
      dependencyMode: 'any',
      targetedRoles: ['protein'],
      requiredChecks: [
        'protein-disease evidence',
        'pathway, phenotype, or mechanistic support',
        'protein-side biological relevance',
      ],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
    {
      id: `H-criterion-disease-target-${sample.sampleIndex}`,
      statement:
        'The disease side explicitly implicates the queried protein as a relevant target or treatment axis.',
      kind: 'criterion',
      status: 'open',
      topicKey: 'criterion.disease-target',
      parentId: positiveRootId,
      childIds: [],
      depth: 1,
      frontier: true,
      dependencyMode: 'any',
      targetedRoles: ['disease'],
      requiredChecks: [
        'disease-target evidence',
        'disease targets, treatments, or biomarkers',
        'disease-side biological relevance',
      ],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
    {
      id: `H-criterion-graph-specificity-${sample.sampleIndex}`,
      statement:
        'The graph side supports the triplet with specific neighborhood structure rather than generic proximity alone.',
      kind: 'criterion',
      status: 'open',
      topicKey: 'criterion.graph-specificity',
      parentId: positiveRootId,
      childIds: [],
      depth: 1,
      frontier: true,
      dependencyMode: 'any',
      targetedRoles: ['graph'],
      requiredChecks: [
        'graph neighborhood support',
        'shared mechanism or disease structure',
        'triplet-level graph coherence',
      ],
      evidenceFor: [],
      evidenceAgainst: [],
      confidence: 0,
      createdRound: 0,
      lastUpdatedRound: 0,
    },
  ];
}
